name: stoneassemblies-massauth-quickstart
network: stoneassemblies-massauth-quickstart-network
services:
- name: stoneassemblies-massauth-quickstart-services
  project: ../../src/StoneAssemblies.MassAuth.QuickStart.Services/StoneAssemblies.MassAuth.QuickStart.Services.csproj
  buildProperties: 
  - name: Configuration
    value: Debug
  env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development
  - name: RabbitMQ:Address
    value: rabbitmq://localhost:6002
  - name: RabbitMQ:Username
    value: queuedemo
  - name: RabbitMQ:Password
    value: queuedemo
  bindings:
  - port: 6001
- name: stoneassemblies-massauth-quickstart-authserver
  project: ../../src/StoneAssemblies.MassAuth.QuickStart.AuthServer/StoneAssemblies.MassAuth.QuickStart.AuthServer.csproj
  replicas: 1
  buildProperties: 
  - name: Configuration
    value: Debug
  env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development
  - name: RabbitMQ:Address
    value: rabbitmq://localhost:6002
  - name: RabbitMQ:Username
    value: queuedemo
  - name: RabbitMQ:Password
    value: queuedemo
  - name: Extensions:Sources:0
    value: ../../output/nuget-symbols/
  - name: Extensions:Sources:1
    value: https://api.nuget.org/v3/index.json
  - name: Extensions:Packages:0
    value: StoneAssemblies.MassAuth.QuickStart.Rules
- name: stoneassemblies-massauth-quickstart-rabbitmq
  image: rabbitmq:3.8.3-management
  bindings:
  - name: rabbitmq
    port: 6002
    containerPort: 5672
    protocol: tcp
  - name: https
    port: 6003
    containerPort: 15672
    protocol: http
  env:
  - name: RABBITMQ_DEFAULT_USER
    value: queuedemo
  - name: RABBITMQ_DEFAULT_PASS
    value: queuedemo